_target_: pytorch_lightning.Trainer

weights_summary: null
gpus: 2
min_epochs: 1
max_epochs: 10
progress_bar_refresh_rate: 10
terminate_on_nan: False
accelerator: "ddp"
replace_sampler_ddp: True # for weighted sampler in v2
deterministic: True
fast_dev_run: False
move_metrics_to_cpu: False
